apiVersion: batch/v1
kind: CronJob
metadata:
  name: cats-dogs-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl
            args: ["-s", "http://cats-dogs-svc.cats-dogs.svc.cluster.local"]
          restartPolicy: OnFailure
